Bufgix: now start if no tunnel is started but file is still present

diff --git a/hpc-tunnel b/hpc-tunnel
--- a/hpc-tunnel
+++ b/hpc-tunnel
@@ -15,21 +15,35 @@ PID_FILE="/tmp/hpc_tunnel_ssh_${PORT}.pid"
 
 
 TUNNEL_SSH_CMD="sshpass -p $TUNNEL_PASS ssh -N -L ${PORT}:elgamal.mat.unimo.it:${PORT} student@wks-marongiu2.mat.unimo.it"
-LOGIN_SSH_CMD="sshpass -p $PASSWORD ssh -X -p $PORT $USER_ID@localhost"
+LOGIN_SSH_CMD="sshpass -p $USER_PASS ssh -X -p $PORT $USER_ID@localhost"
 
 
 case $1 in
     start)
         if [ -f "$PID_FILE" ]; then
-            echo "Errore: il tunnel SSH è già in esecuzione sulla porta $PORT (PID: $(cat $PID_FILE))"
-            exit 1
+            SSH_PID=$(cat "$PID_FILE")
+            
+            if ps -p $SSH_PID > /dev/null 2>&1; then
+                if ps -p $SSH_PID -o cmd= | grep -q "ssh"; then
+                    echo "Errore: il tunnel SSH è già in esecuzione sulla porta $PORT (PID: $SSH_PID)"
+                    exit 1
+                else
+                    #echo "Il PID $SSH_PID non è associato a un processo SSH. Rimuovo il file PID."
+                    rm "$PID_FILE"
+                fi
+            else
+                #echo "Il processo con PID $SSH_PID non è attivo. Rimuovo il file PID."
+                rm "$PID_FILE"
+            fi
         fi
+
         echo "Avvio del tunnel SSH sulla porta $PORT in background..."
-        eval "$TUNNEL_SSH_CMD &"  
-        SSH_PID=$!          
+        eval "$TUNNEL_SSH_CMD &"
+        SSH_PID=$!
         echo $SSH_PID > "$PID_FILE"
         echo "Tunnel SSH avviato con PID: $SSH_PID"
         ;;
+        
     stop)
         if [ ! -f "$PID_FILE" ]; then
             echo "Errore: nessun tunnel SSH attivo sulla porta $PORT"
@@ -41,12 +55,13 @@ case $1 in
         rm "$PID_FILE"
         echo "Tunnel SSH terminato."
         ;;
+        
     login)
         eval "$LOGIN_SSH_CMD"
         ;;
+        
     *)
         echo "Errore: il primo parametro deve essere 'start', 'stop' o 'login'."
         exit 1
         ;;
 esac
-
